domains:
  - domain: bluemwhitew.photography
    type: PRIMARY
    zone: bluemwhitew.photography
envs:
  - key: CONTENTFUL_ACCESS_TOKEN_DELIVERY_API
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CONTENTFUL_ACCESS_TOKEN_PREVIEW_API
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CONTENTFUL_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
  - key: CONTENTFUL_SPACE_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_TAG_MANAGER_TAG_ID
    scope: RUN_AND_BUILD_TIME
ingress:
  rules:
    - component:
        name: bluemwhitew-photography
      match:
        path:
          prefix: /
name: bluemwhitew-photography
region: lon
static_sites:
  - build_command: |
      npm run tailwind:build
      npm run eleventy:build
    environment_slug: node-js
    envs:
      - key: HUSKY
        scope: BUILD_TIME
        value: "0"
      - key: NPM_CONFIG_PRODUCTION
        scope: BUILD_TIME
        value: "true"
    github:
      branch: master
      repo: bluemwhitew/bluemwhitew.photography
    name: bluemwhitew-photography
    output_dir: dist
    source_dir: /
