name: Deploy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    env:
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NODE_ENV: production
    if: github.repository == 'bluemwhitew/bluemwhitew.photography'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.x'

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            ${{ runner.os }}-node-

      - run: |
          echo "Build #$GITHUB_SHA" > ./src/_includes/footer/build-information/information.liquid
      - run: npm ci
      - run: npm run postcss
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          overwrite: true
          port: ${{ secrets.PORT }}
          source: "dist/*"
          strip_components: 1
          target: ${{ secrets.TARGET }} # "/var/www/x1908"
          username: ${{ secrets.USERNAME }}
