name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}

permissions:
  contents: read

jobs:
  deploy:
    env:
      CONTENTFUL_ACCESS_TOKEN_DELIVERY_API: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_DELIVERY_API }}
      CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      HUSKY: 0
      NODE_ENV: production
    if: github.repository == 'bluemwhitew/bluemwhitew.photography'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json
          node-version: "22.18"
      - run: |
          echo "Build #$GITHUB_SHA" > ${{ github.workspace }}/src/_includes/footer/build-information/information.liquid
          npm ci
          npm run tailwind:build
          npm run eleventy:build

      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          overwrite: true
          port: ${{ secrets.PORT }}
          source: "dist/*"
          strip_components: 1
          target: ${{ secrets.TARGET }} # "/var/www/x1908"
          username: ${{ secrets.USERNAME }}
