name: Deploy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'bluemwhitew/bluemwhitew.photography'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.x'

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: ${{ secrets.TARGET }} # "/var/www/x1908"
          username: ${{ secrets.USERNAME }}
